// Benjamin Ward, Jan 13, 2015

#ifndef LATCH_CPP_SRC_DATALOGGING_H_
#define LATCH_CPP_SRC_DATALOGGING_H_

#include <iostream>
#include <fstream>
#include <time.h>

#include "WPILib.h"

typedef std::string string;

class DataLogging
{
public:
	DataLogging();
	~DataLogging();
	short Log(string);
	short Log(string*, int); // Takes a list of strings generated by the user of the function
	short Log(SpeedController*, int); // Takes a list of SpeedControllers aka Talons, TalonSRXs, etc
	short Log(Joystick*);

private:
	string* bufferedText;
	int bufferSize;
	const int maxBufferSize = 64;
	void writeBuffer();
	int fileNumber = 0;
	const string fileName = "DataLog";
	std::ofstream file;
	string getTime();
	time_t rawtime;
	struct tm* timeinfo;

};

#endif /* LATCH_CPP_SRC_DATALOGGING_H_ */
